name: /Users/raineyaberle/opt/anaconda3/envs/skysat_stereo/planet-snow
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=20.1.0=py38h9ed2024_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py38hecd8cb5_0
  - cffi=1.14.6=py38h2125817_0
  - dbus=1.13.18=h18a8e69_0
  - debugpy=1.5.1=py38he9d5cce_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.1=h23ab428_2
  - gettext=0.21.0=h7535e17_0
  - glib=2.69.1=hdf23fa2_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=4.8.2=py38hecd8cb5_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipykernel=6.4.1=py38hecd8cb5_1
  - ipython=7.29.0=py38h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py38hecd8cb5_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libxml2=2.9.12=hcdb78fc_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - markupsafe=2.0.1=py38h9ed2024_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h1de35cc_1001
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py38hecd8cb5_0
  - openssl=1.1.1l=h9ed2024_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38hecd8cb5_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.18.0=py38hca72f7f_0
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.3.0=py38he9d5cce_2
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38hecd8cb5_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=h707629a_0
  - terminado=0.9.4=py38hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h7bc2e8c_0
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h4dc903c_4
  - pip:
    - affine==2.3.0
    - charset-normalizer==2.0.9
    - click==8.0.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cycler==0.11.0
    - earthpy==0.9.4
    - fiona==1.8.20
    - fonttools==4.28.5
    - geopandas==0.10.2
    - idna==3.3
    - imageio==2.13.5
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - munch==2.5.0
    - networkx==2.6.3
    - numpy==1.21.5
    - pandas==1.3.5
    - pillow==8.4.0
    - pyproj==3.3.0
    - pytz==2021.3
    - pywavelets==1.2.0
    - rasterio==1.2.10
    - requests==2.26.0
    - scikit-image==0.19.1
    - scipy==1.7.3
    - shapely==1.8.0
    - snuggs==1.4.7
    - tifffile==2021.11.2
    - urllib3==1.26.7
prefix: /Users/raineyaberle/opt/anaconda3/envs/skysat_stereo/planet-snow
